import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';

export default defineConfig({
    plugins: [
        laravel({
            input: [
                'resources/css/app.css',
                'resources/js/app.js',
                'public/backend/assets/vendors/core/core.css',
                'public/backend/assets/vendors/flatpickr/flatpickr.min.css',
                'public/backend/assets/fonts/feather-font/css/iconfont.css',
                'public/backend/assets/vendors/flag-icon-css/css/flag-icon.min.css',
                'public/backend/assets/css/demo2/style.css',
                'public/backend/assets/images/favicon.png',
                'public/backend/assets/vendors/core/core.js',
                'public/backend/assets/vendors/flatpickr/flatpickr.min.js',
                'public/backend/assets/vendors/apexcharts/apexcharts.min.js',
                'public/backend/assets/vendors/feather-icons/feather.min.js',
                'public/backend/assets/js/template.js',
                'public/backend/assets/js/dashboard-dark.js',
                'public/upload/login.png',
                'public/upload/no_image.jpg',
                'public/frontend/assets/css/font-awesome-all.css',
                'public/frontend/assets/css/flaticon.css',
                'public/frontend/assets/css/owl.css',
                'public/frontend/assets/css/bootstrap.css',
                'public/frontend/assets/css/jquery.fancybox.min.css',
                'public/frontend/assets/css/animate.css',
                'public/frontend/assets/css/jquery-ui.css',
                'public/frontend/assets/css/nice-select.css',
                'public/frontend/assets/css/color/theme-color.css',
                'public/frontend/assets/css/switcher-style.css',
                'public/frontend/assets/css/style.css',
                'public/frontend/assets/css/responsive.css',
                'public/frontend/assets/js/jquery.js',
                'public/frontend/assets/js/popper.min.js',
                'public/frontend/assets/js/bootstrap.min.js',
                'public/frontend/assets/js/owl.js',
                'public/frontend/assets/js/wow.js',
                'public/frontend/assets/js/validation.js',
                'public/frontend/assets/js/jquery.fancybox.js',
                'public/frontend/assets/js/appear.js',
                'public/frontend/assets/js/scrollbar.js',
                'public/frontend/assets/js/isotope.js',
                'public/frontend/assets/js/jquery.nice-select.min.js',
                'public/frontend/assets/js/jQuery.style.switcher.min.js',
                'public/frontend/assets/js/jquery-ui.js',
                'public/frontend/assets/js/nav-tool.js',
                'public/frontend/assets/js/script.js',
                'public/backend/assets/vendors/sweetalert2/sweetalert2.min.js',
                'public/backend/assets/js/sweet-alert.js',
                'public/backend/assets/js/code/code.js',
                'public/backend/assets/js/code/validate.min.js',
                'public/backend/assets/vendors/select2/select2.min.css',
                'public/backend/assets/vendors/jquery-tags-input/jquery.tagsinput.min.css',
                'public/backend/assets/vendors/inputmask/jquery.inputmask.min.js',
                'public/backend/assets/vendors/select2/select2.min.js',
                'public/backend/assets/vendors/typeahead.js/typeahead.bundle.min.js',
                'public/backend/assets/vendors/jquery-tags-input/jquery.tagsinput.min.js',
                'public/backend/assets/js/inputmask.js',
                'public/backend/assets/js/select2.js',
                'public/backend/assets/js/typeahead.js',
                'public/backend/assets/js/tags-input.js',
                'public/backend/assets/vendors/tinymce/tinymce.min.js',
                'public/backend/assets/js/tinymce.js'
            ],
            refresh: true,
        }),
    ],
});
